export const endpoints = {
  auth: {
    login: '/users/login',
    register: '/users/register',
    profile: '/users/profile',
    refresh: '/users/refresh',
    verifyOtp: '/users/verify-otp',
  },
  vehicles: {
    list: '/users/vehicles',
    create: '/users/vehicles',
  },
  rides: {
    base: '/rides',
    search: '/rides/search',
    myRides: '/rides/my-rides',
    myBookings: '/rides/my-bookings',
    calculateFare: '/rides/calculate-fare',
    addressSuggestions: '/rides/address-suggestions',
    status: (rideId) => `/rides/${rideId}/status`,
    detail: (rideId) => `/rides/${rideId}`,
    update: (rideId) => `/rides/${rideId}`,
    cancel: (rideId) => `/rides/${rideId}`,
    book: (rideId) => `/rides/${rideId}/book`,
    verifyPayment: (bookingId) => `/rides/bookings/${bookingId}/verify-payment`,
    verifyOtp: (bookingId) => `/rides/bookings/${bookingId}/verify-otp`,
    sendOtp: (bookingId) => `/rides/bookings/${bookingId}/send-otp`,
    rideBookings: (rideId) => `/rides/${rideId}/bookings`,
  },
  payments: {
    initiate: '/payments/initiate',
    verify: '/payments/verify',
    transactions: '/payments/transactions',
    booking: (bookingId) => `/payments/booking/${bookingId}`,
    paymentOrder: (paymentId) => `/payments/${paymentId}/order`,
    wallet: (userId) => `/payments/wallet/${userId}`,
    walletTransactions: (userId) => `/payments/wallet/${userId}/transactions`,
    bankAccounts: '/payments/bank-accounts',
    bankAccount: (accountId) => `/payments/bank-accounts/${accountId}`,
    setDefaultBankAccount: (accountId) => `/payments/bank-accounts/${accountId}/default`,
    withdrawals: '/payments/withdrawals',
    withdrawal: (withdrawalId) => `/payments/withdrawals/${withdrawalId}`,
  },
  reviews: {
    passenger: (bookingId) => `/reviews/passenger/${bookingId}`,
    driver: (bookingId) => `/reviews/driver/${bookingId}`,
    user: (userId) => `/reviews/user/${userId}`,
    userRating: (userId) => `/reviews/user/${userId}/rating`,
    booking: (bookingId) => `/reviews/booking/${bookingId}`,
    check: (bookingId) => `/reviews/booking/${bookingId}/check`,
  },
}

export default endpoints

